import React from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '../components/ui/card';
import { Button } from '../components/ui/button';
import { Sparkles, Users, Globe, ArrowRight, Star } from 'lucide-react';

export const CommunityPage: React.FC = () => {
  const featuredComponents = [
    {
      name: "Glassmorphic Card",
      author: "Alex Rivers",
      stars: 124,
      preview: "bg-gradient-to-br from-indigo-500 to-purple-600"
    },
    {
      name: "Neo-Brutalist Button",
      author: "Sarah Chen",
      stars: 89,
      preview: "bg-yellow-400 border-4 border-black"
    },
    {
      name: "Aurora Background",
      author: "Mike Ross",
      stars: 256,
      preview: "bg-slate-950 overflow-hidden"
    }
  ];

  return (
    <div className="p-8 max-w-7xl mx-auto space-y-12">
      <div className="text-center space-y-4">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-primary/10 text-primary text-sm font-medium">
          <Globe className="w-4 h-4" />
          <span>Community Showcase</span>
        </div>
        <h1 className="text-4xl font-bold tracking-tight">Explore the Gallery</h1>
        <p className="text-muted-foreground text-lg max-w-2xl mx-auto">
          Discover beautiful components generated by creators around the world.
          Copy, remix, and share your own creations.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
        <Card className="bg-primary text-primary-foreground border-none">
          <CardHeader>
            <Users className="w-8 h-8 mb-2" />
            <CardTitle>1.2k Creators</CardTitle>
            <CardDescription className="text-primary-foreground/70">Joined the community this week</CardDescription>
          </CardHeader>
        </Card>
        <Card className="border-2 border-primary/10">
          <CardHeader>
            <Sparkles className="w-8 h-8 mb-2 text-primary" />
            <CardTitle>5.4k Components</CardTitle>
            <CardDescription>Generated and shared globally</CardDescription>
          </CardHeader>
        </Card>
        <Card className="border-2 border-primary/10">
          <CardHeader>
            <Star className="w-8 h-8 mb-2 text-primary" />
            <CardTitle>Top Rated</CardTitle>
            <CardDescription>Hand-picked components of the month</CardDescription>
          </CardHeader>
        </Card>
      </div>

      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <h2 className="text-2xl font-bold">Featured Components</h2>
          <Button variant="ghost" className="gap-2">
            View all <ArrowRight className="w-4 h-4" />
          </Button>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {featuredComponents.map((comp, i) => (
            <Card key={i} className="group overflow-hidden hover:shadow-xl transition-all border-primary/5 hover:border-primary/20">
              <div className={`h-48 ${comp.preview} relative p-4 flex items-center justify-center`}>
                 <div className="w-24 h-24 bg-white/10 backdrop-blur-md rounded-xl border border-white/20 animate-pulse" />
                 <div className="absolute top-4 right-4 bg-black/20 backdrop-blur-sm text-white px-2 py-1 rounded text-xs flex items-center gap-1">
                   <Star className="w-3 h-3 fill-yellow-400 text-yellow-400" />
                   {comp.stars}
                 </div>
              </div>
              <CardHeader className="p-4">
                <CardTitle className="text-lg">{comp.name}</CardTitle>
                <CardDescription>by @{comp.author.toLowerCase().replace(' ', '')}</CardDescription>
              </CardHeader>
              <CardContent className="p-4 pt-0">
                <Button variant="outline" className="w-full gap-2">
                  Remix this
                </Button>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>

      <div className="bg-muted/30 rounded-2xl p-12 text-center space-y-6 border border-dashed">
        <div className="w-16 h-16 bg-background rounded-2xl border flex items-center justify-center mx-auto shadow-sm">
          <Sparkles className="w-8 h-8 text-primary" />
        </div>
        <div className="space-y-2">
          <h3 className="text-xl font-bold">Share your own Genie magic</h3>
          <p className="text-muted-foreground">Publish your components to the community and help others build faster.</p>
        </div>
        <Button size="lg" className="rounded-full px-8">
          Start Generating
        </Button>
      </div>
    </div>
  );
};
